Pelias autocompletion
blackforestsolutions/dravelopsdatamodel pull request #21
Opened 2020-10-28 14:54 UTC by hennihaus

2020-10-28 15:35 UTC, mburkertt requested changes
Ich habe zwei Anmerkungen gemacht.

2020-10-28 15:35 UTC, mburkertt commented on src/main/java/de/blackforestsolutions/dravelopsdatamodel/util/ApiToken.java
>          @SuppressWarnings("CPD-START")
Warn surpression ?

2020-10-28 15:35 UTC, mburkertt commented on src/main/java/de/blackforestsolutions/dravelopsdatamodel/util/ApiToken.java
>          @SuppressWarnings("CPD-START")
Warn surpression ?

2020-10-28 15:50 UTC, hennihaus commented on src/main/java/de/blackforestsolutions/dravelopsdatamodel/util/ApiToken.java
>          @SuppressWarnings("CPD-START")
I have made comments in code.

2020-10-28 15:50 UTC, hennihaus commented on src/main/java/de/blackforestsolutions/dravelopsdatamodel/util/ApiToken.java
>          @SuppressWarnings("CPD-START")
I have made comments in code.

2020-11-01 09:15 UTC, jobdk approved these changes
Looks good to me. But @mburkertt should check your changes as well.

2020-11-01 16:59 UTC, mburkertt approved these changes
OK alles geklärt.

2020-11-01 17:00 UTC, merged